### ISSUE TITLE
hGetLine does not exists

### ISSUE THREAD

**Issue by b3z** [Lysxia/roll-your-own-irc-bot#2]
I have no idea how haskell works so I wanted to just play around a little to learn it but I am getting this error message.

```sh
$ stack exec bot-2
> NICK tutbot
> USER tutbot 0 * :tutorial bot
> JOIN #tutbot-testing
bot-2: <socket: 14>: hGetLine: does not exist (Connection refused)
```

**Comment by Lysxia** [comment]
I must admit I'm not sure how to troubleshoot this, though it probably has more to do with networking than Haskell. Do you have no trouble connecting to IRC through another application?

**Comment by b3z** [comment]
No issues with other applications (weechat)
